Cwc 105
CoolBitX-Technology/coolwallet3-sdk pull request #54
Opened 2020-10-22 07:17 UTC by iancoolbitx

2020-10-22 11:09 UTC, hankliu418 commented on packages/cws-icx/src/util.ts
> +  console.log(argument)
remove console

2020-10-22 11:12 UTC, hankliu418 requested changes
please remove console.log

2020-10-23 02:39 UTC, skchang0710 submitted a review, later dismissed

2020-10-23 02:53 UTC, skchang0710 approved these changes

2020-10-23 03:07 UTC, hankliu418 approved these changes

2020-10-23 03:08 UTC, merged